safe:        false
base-url:    /
permalink: /:categories/:year-:month-:day/:title.html
excerpt_separator: <!--more-->
paginate: 9
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate]

source:      .
destination: ./_site
plugins_dir:     ./_plugins
url: http://starwarswars.com

future:      false
lsi:         false
highlighter:    false
markdown:    kramdown
relative_permalinks: false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style